/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Third_section.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[-4.1, 0.99, 4.19]} rotation={[1.89, 0.88, -2.05]}>
          <pointLight name="Light_Orientation" intensity={1000} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Camera" position={[-4.52, 2.35, -1.86]} rotation={[1.65, -0.53, 1.81]}>
          <PerspectiveCamera name="Camera_Orientation" makeDefault={false} far={100} near={0.1} fov={25.9} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Light001" position={[0.3, 2.16, -3.88]} rotation={[1.89, 0.88, -2.05]}>
          <pointLight name="Light001_Orientation" intensity={500} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.004']} position={[-1.41, -0.03, -0.08]} rotation={[3.13, 0, 0]} scale={[-0.21, -0.15, -0.14]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.004']} position={[-1.02, -0.04, -0.08]} rotation={[-1.58, 0, 0]} scale={[0.39, 0.19, 0.27]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[-1.05, -0.06, -0.28]} rotation={[1.61, 1.57, 3.09]} scale={-0.01} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.006']} position={[-1.02, -0.04, -0.27]} rotation={[-1.57, 0, 0]} scale={0.06} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.003']} position={[-1.05, -0.01, -0.28]} rotation={[1.61, 1.57, 3.09]} scale={-0.01} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-0.99, -0.04, -0.28]} rotation={[1.61, 1.57, 3.09]} scale={-0.01} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.005']} position={[-4.82, -0.03, -0.07]} rotation={[1.89, 0, 1.57]} scale={[-0.03, -0.01, -0.03]} />
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['Material.004']} position={[-1.74, -0.03, -0.08]} rotation={[1.61, 1.57, 3.09]} scale={[0.14, 0.21, 0.2]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.005']} morphTargetDictionary={nodes.Plane009.morphTargetDictionary} morphTargetInfluences={nodes.Plane009.morphTargetInfluences} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.005']} morphTargetDictionary={nodes.Plane001.morphTargetDictionary} morphTargetInfluences={nodes.Plane001.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('/Third_section.glb')
