export default {
  first: {
    sphereAnimation: {
      target: "First",
      rotate: "0deg",
      translateX: [2, -4],
      translateY: [2, -4],
      percent: 1,
    },
    xPos: -9,
    yPos: -9,
    scale: 1,
    xPosRatio: 1.5,
    yPosRatio: 2,
    scaleRatio: 0.1,
    name: "first",
    target: "First",
  },
  two: {
    sphereAnimation: {
      target: "Two",
      rotate: "90deg",
      translateX: [4, 8],
      translateY: [12, 4],
      percent: -1,
    },
    xPos: -17,
    yPos: 8,
    scale: 1.1,
    xPosRatio: 4,
    yPosRatio: 4.8,
    scaleRatio: 0.1,
    name: "two",
    target: "Two",
  },
  three: {
    sphereAnimation: {
      target: "Three",
      rotate: "90deg",
      translateX: [4, 8],
      translateY: [12, 4],
      percent: -1,
    },
    xPos: 9,
    yPos: 3,
    scale: 1,
    xPosRatio: 6,
    yPosRatio: 5,
    scaleRatio: 0.2,
    name: "three",
    target: "Three",
  },
};
